# NOTE: Generated By HttpRunner v3.1.6
# FROM: .\har\login.har
import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase



@pytest.mark.login
class TestCaseLogin(HttpRunner):

    config = Config("登录").base_url("${ENV(BASE_URL)}").verify(False)

    teststeps = [
        Step(
            RunRequest("登陆login")
            .post("/api/login")
            .with_headers(
                **{
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "${get_httprunner_version()}"
                }
            )
            .with_json(
                {
                    "password": "${ENV(PASSWORD)}",
                    "phoneNumber": "${ENV(USERNAME)}",
                    "uuid": "xxx-xxx-xxx-xxx"
                }
            )
            .extract()
            .with_jmespath("body.data.token","token") # todo 先extract后jmspath提取并赋值
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "登录成功")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
